#!/bin/sh
#
# ~/.xinitrc
#

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Custom X Resources
xrdb -load ~/.config/X11/xresources

# set Screens
xrandr_both

# set Wallpaper
fehbg

# Notification Daemon (autostarted by lxde currently)
#dunst &

# Power Savings
xset s 1800 1800
xset dpms 1800 1800 1800

# make TCL/TK theme (from pysolfc) available
export TCLLIBPATH=~/.local/share/tkthemes

# set graphical ssh password prompt
export SSH_ASKPASS=/usr/lib/ssh/x11-ssh-askpass

# provide error log
#mv .xsession-errors .xsession-errors.old

# start Window Manager
#exec i3 &> .xsession-errors
exec startlxde
